### ISSUE TITLE
support for the instance directory being named `minecraft` instead of `.minecraft`

### ISSUE THREAD

**Issue by maskersss** [tildejustin/modcheck#13]
https://github.com/PrismLauncher/PrismLauncher/pull/2050 i believe prism will be changing it in the future, since it's changed in https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop

**Comment by tildejustin** [comment]
as i've heard, multimc also supports this folder naming

**Comment by maskersss** [comment]
3.0.1 works for me both when selecting the `minecraft` folder and the folder one above it
